const exercise = [
    {
      id: 1,
      title: 'sit up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/situp.jpg',
      vid: 'https://www.youtube.com/embed/jDwoBqPH0jk',
      desc: `1. Lie down on your back with your knees up and hands placed behind your head.\n2. Breathe out and squeeze your abs to feel the tension as you bring your upper half off the floor.\n3. Once your upper half is 65 degrees off the floor, slowly lower your upper half back to the floor.\n4. Repeat this exercise aslong as possible (best to do for 12 times). `,
    },
    {
      id: 2,
      title: 'lying floor leg raise',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/lyingleg2.jpg',
      vid: 'https://www.youtube.com/embed/l4kQd9eWclE',
      desc: `1. Lie down on your back and keep your legs straight.\n2. Make sure your legs are straight now raise them up.\n3. Once you raised your legs to a 90 degree angle, bring your legs back to the starting position.\n4. Can repeat this exercise for 12 reps or more. `,
    },
    {
      id: 3,
      title: 'pushup',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/pushup.jpg',
      vid: 'https://www.youtube.com/embed/KEFQyLkDYtI',
      desc: `1. Lie down with your face, facing the floor.\n2. Arms fully stretched out in a pushing position, body and legs fully extended out in a plank position.\n3. Slowly bring your body down to the floor, chest touching the floor. Drawing back your shoulder blades and ensuring elbows are bent.\n4. Now push your body back to starting position by extending your arms and using your hands to push off the floor.\n5. Repeat this exercises for as many reps you can do`,
    },
    {
      id: 4,
      title: 'bicycle',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/bicycle2.jpg',
      vid: 'https://www.youtube.com/embed/1we3bh9uhqY',
      desc: `1. Lie down on your back with your hands behind your head and legs straight.\n2. Breathe out as you bring one knee towards your face while bringing your opposite elbow to touch that knee.\n3. Upon feeling tenstion on your abs, bring your knee back to the starting position and repeat on the opposite side.\n4. Do this exercise for as many reps you can do. `,
    },
    {
      id: 5,
      title: 'dumbbell bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/dumbbellbenchpress3.jpeg',
      vid: 'https://www.youtube.com/embed/dGqI0Z5ul4k',
      desc: `1. Choose your desired weight of dumbbells and sit down on the bench.\n2. Lie down on your back and bring the dumbbells close to your chest. Once you are in this position inhale, push the dumbells outwards.\n3. Slowly lower the dumbbels while controlling it, bring it down till your elbows are bent with the handles being on the same level as chest.\n4. Now push the dumbbells up again.\n5. Repeat this exercise for a certain amount of times approximately 8-12 times. `,
    },
    {
      id: 6,
      title: 'seated cable row',
      category: 'back',
      experience: 'beginner',
      img: './images/seatedcablerow.jpg',
      vid: 'https://www.youtube.com/embed/GZbfZ033f74',
      desc: `1. Attach a close grip bar or V bar to the seated cable row machine after choosing the desired weight.\n2. Using a neutral grip to hold the bar with your palms facing in.\n3. Pull the weight towards you while maintaining a straight back and slightly bending your knees.\n4. Ensure you stay in this position, pull the bar towards your belly button.\n5. Ensure you pull your shoulder blades back, feel the tension and then slowly push the weight away back to the start position  \n6. Repeat this exercise for as many reps as you desire.`,
    },
    {
      id: 7,
      title: 'incline dumbbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/inclinedumbell.jpg',
      vid: 'https://www.youtube.com/embed/07Bcqtib4FM',
      desc: `1. Select a dumbbell weight then adjust the bench to an incline position which is around 55-65 degree angle, then sit up straight with your back against the bench.\n2. Grab the dumbbells with your palms facing you , inhale and curl both dumbbells towards your shoulders.\n3. Slowly lower the dumbbells back to the starting position after the biceps have fully contracted.\n4. Do this exercise for an appropriate number of times,approximately 8 to 12 reps. `,
    },
    {
      id: 8,
      title: 'rope tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/ropetricep.jpg',
      vid: 'https://www.youtube.com/embed/LzwgB15UdO8',
      desc: `1. In a standing position, attach a rope to cable machine and adjust the cable to as high as possible.\n2. Hold the rope with your palms facing in and lean slightly forward.\n3. Start by flexing the triceps and extending the elbows.\n4. Pull the rope down until your elbows are nearly fully extended and then controlling the tension slowly bring them back to the starting position.\n5. Repeat this exercise for as many reps as you would like. `,
    },
    {
      id: 9,
      title: 'seated leg curl',
      category: 'legs',
      experience: 'beginner',
      img: './images/seatedlegcurl.jpg',
      vid: 'https://www.youtube.com/embed/3BWiLFc8Dbg',
      desc: `1. Choose the weight that suits you, then position the pad so it rests comfortably on the back of your heels.\n2. Inhale, squeeze the hamstrings, and bring your legs up as far as possible.\n4. Controlling the weight, slowly lower your legs down back to the start position and repeat this exercise for a number times.`,
    },
    {
      id: 10,
      title: 'barbell bench press',
      category: 'chest',
      experience: 'intermediate',
      img: './images/barbellbenchpress.jpg',
      vid: 'https://www.youtube.com/embed/4aVy2Xj6wYs',
      desc: `1. Lie on your back on the bench and place your hands so it is slightly wider than your shoulder width.\n2. Bring your shoulder blades close together and push your shoulder blades into the bench.\n3. Inhale and allow your spotter to help you with the lift off to ensure you still feel the tension through your upper back.\n4. After lifting the bar, let the weight rest and make sure your upper back is still firm.\n5. Take a deep breath and then slowly lower the bar by bending the elbows.\n6. Lower the bar in a straight line till it touches your chest.\n7. Push the bar back up in a straight line by pressing shoulder blades into the bench, using your legs as support by pushing against the floor, and extending the elbows.\n8. Repeat this exercise for as many reps as possible.`,
    },
    {
      id: 11,
      title: 'incline bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/inclinebench.jpg',
      vid: 'https://www.youtube.com/embed/dtNXLavPFo0',
      desc: `1. Lie on your back on the bench and place your hands so it is slightly wider than your shoulder width.\n2. Bring your shoulder blades close together and push your shoulder blades into the bench.\n3. Inhale and allow your spotter to help you with lifting the bar off to ensure you still feel the tension through your upper back.\n4. After lifting the bar, let the weight rest and make sure your upper back is still firm.\n5. Take a deep breath and then slowly lower the bar by bending your elbows.\n6. Lower the bar in a straight line till it touches your chest.\n7. Push the bar back up in a straight line by pressing shoulder blades into the bench, using your legs as support by pushing against the floor, and extending the elbows.\n8. Repeat for as many times as possible.`,
    },
    {
      id: 12,
      title: 'chest fly',
      category: 'chest',
      experience: 'beginner',
      img: './images/chestfly.jpg',
      vid: 'https://www.youtube.com/embed/Z57CtFmRMxA',
      desc: `1. Adjust the seat height to fit your height.\n2. Choose your desired weight.\n3. Sit down on the seat, grip the handles on the machine.\n4. Ensure you are sitting straight, slowly bring the handles together. Don't let them touch.\n5. Tense the chest muscles for a count of 1-3, then slowly lower the handles back to the starting position.\n6. Repeat this for the desired reps`,
    },
    {
      id: 13,
      title: 'chest dip',
      category: 'chest',
      experience: 'intermediate',
      img: './images/chestdip.jpg',
      vid: 'https://www.youtube.com/embed/FG1ENBFsdHU',
      desc: `1. Position your hands with your palms facing the handles.\n2. Start the dip by bending your elbows and slowly lowering your body down.\n3. Control the tenstion and then fully extend your elbows by pushing your palms through the handles.\n4. Repeat this exercise for a desired number of times.`,
    },
    {
      id: 14,
      title: 'standing dumbbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standingdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/ykJmrZ5v0Oo',
      desc: `1. Standing up,gripping the dumbbells, the dumbbells should be beside you.\n2. Your palms should be facing the ceiling.\n3. Bend your elbows slightly, you should feel tension on your biceps.\n4. Slowly curl the dumbbells up as far as possible.\n5. Feel the tension on the biceps by squeezing , slowly lower the dumbbells down.\n6. Repeat for a number of times.`,
    },
    {
      id: 15,
      title: 'standing barbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standingbar.jpg',
      vid: 'https://www.youtube.com/embed/kwG2ipFRgfo',
      desc: `1. Grip onto a barbell at around shoulder width apart with your palms facing up.\n2. Standing with feet together ensure your back is straight, and with your arms fully extended.\n3. The bar should not be touching your body.\n4. Keeping your head facing forwards, elbows tucked in at your sides, and with your back straight, slowly curl the bar up.\n5. Squeeze your biceps hard when the bar reaches your upper chest, and then slowly lower it back down.\n6. Repeat this for a number reps.`,
    },
    {
      id: 16,
      title: 'bent over row',
      category: 'back',
      experience: 'beginner',
      img: './images/bentoverrow.jpg',
      vid: 'https://www.youtube.com/embed/paCfxhgW6bI',
      desc: `1. In a standing position grasp the bar using a double overhand grip.\n2. Lean forward until your upper body is slightly parallel with the floor and thrust the elbows behind your body and retract the shoulder blades.\n3. Pull the bar towards you until it touches your stomach and controlling the tension slowly lower the bar.\n4. Repeat for a number of times.`,
    },
    {
      id: 17,
      title: 'dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/dumbbellrow.jpg',
      vid: 'https://www.youtube.com/embed/-koP10y1qZI',
      desc: `1. Kneel on the bench with the hand that is on the same side as the knee place it on the bench.\n2. Grasp a dumbbell in the opposite side of the knee with a neutral grip.\n3. Bring the elbow behind the body while retracting the shoulder blade.\n4. Pull the dumbbell towards you until the elbow is at your side then controlling the tension slowly lower the dumbbell.\n5. Repeat this exercise on both sides for a number of reps.`,
    },
    {
      id: 18,
      title: 'lat pulldown',
      category: 'back',
      experience: 'beginner',
      img: './images/latpulldown.jpg',
      vid: 'https://www.youtube.com/embed/u3gQT2aMVaI',
      desc: `1. Attach a wide grip handle on the lat pulldown machine and then sit down on the seat.\n2. Hold the handle with a double hand grip and then pull down.\n3. Pull the handle down until the elbows are beside your ribs area and then slowly bring the handle bar back up.\n4. Repeat this exercise for a number of reps.`,
    },
    {
      id: 19,
      title: 'concentration curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/concentrationcurl.jpg',
      vid: 'https://www.youtube.com/embed/0AUGkch3tzc',
      desc: `1. Choose your desired weight and then sit on the bench with a straight back.\n2. Lean slightly forward and place your elbow near your kneecap. Rest your other hand on the opposite knee to help you stay balanced.\n3. Your palms should be facing up, inhale and curl the dumbbell towards your shoulder.\n4. Once the bicep is fully contracted, controlling the dumbbell slowly bring it down.\n5. Repeat this for a number of reps on both sides.`,
    },
    {
      id: 20,
      title: 'straight bar tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/straightbar.jpeg',
      vid: 'https://www.youtube.com/embed/LlBqt8dksdk',
      desc: `1. While standing, attach a straight bar to the cable machine and ensure it's placed as high as possible.\n2. Gripping the straight bar with your palms facing the ground, tilt your body slightly forward. \n3. Tense your triceps and extend your elbows.\n4. Pull the handle downward until the elbows are almost fully extended out and controlling the tension slowly lower it.\n5. Repeat this for a number of times.`,
    },
    {
      id: 21,
      title: 'two arm standing dumbbell extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/standingdumbbelltricep2.jpg',
      vid: 'https://www.youtube.com/embed/VjmgzEmODnI',
      desc: `1. Choose a weight then ensure you are standing away in a open space.\n2. Lift the dumbbell over your head ,inhale, overlap your hands around the dumbbell, then lower the dumbbell behind your head with elbows bent.\n3. Then bring the dumbbell back to above your head.\n4. Repeat this exercise for a number of repetitions.`,
    },
    {
      id: 22,
      title: 'one arm standing dumbbell extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/onearm.jpeg',
      vid: 'https://www.youtube.com/embed/_gsUck-7M74',
      desc: `1. Standing in a open space holding the dumbbell above your head with your palm facing forward.\n2. Your elbow should be slightly bent. You can use your other hand to help maintain your balance.\n3. Bend your elbow and lower it till it reaches your neck.\n4. Once the dumbbel reaches this area of your neck should feel tension, controlling the tension bring the dumbbell back to above your head.\n5. Ensure your elbows are still slightly bent when you reach the start position, and then repeat this for as many reps you like.`,
    },
    {
      id: 23,
      title: 'leg press',
      category: 'legs',
      experience: 'beginner',
      img: './images/legpress.jpg',
      vid: 'https://www.youtube.com/embed/VFk3RzndUEc',
      desc: `1. Choose the desired weight and place your back against the padded seat and with your legs against the machine.\n2. Place your legs so that they aligned with your shoulder width.\n3. Inhale, extend your legs, and unlock the safeties.\n4. Controlling the weight slowly lower it until its 45 degree angle.\n5. Push the weight back to starting position do not fully extend your legs.\n6. Repeat for a number of reps.`,
    },
    {
      id: 24,
      title: 'seated calf raise',
      category: 'legs',
      experience: 'beginner',
      img: './images/seatedcalfraise.jpg',
      vid: 'https://www.youtube.com/embed/JbyjNymZOt0',
      desc: `1. Sit on the machine and place the balls of your feet on the platform. \n2. Extend your ankles and release the safety bar.\n3. Lift your heels up off the platform.\n4. Hold the tension and controlling the tension lower your heel back down.\n5. Repeat this for a number of reps.`,
    },
    {
      id: 25,
      title: 'barbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/barbellsquat.jpg',
      vid: 'https://www.youtube.com/embed/MVMNk0HiTMg',
      desc: `1. To start this exercise first load the amount of weights you would like to use, and then set the barbell to below shoulder height.\n2. Now stand under the barbell with feet apart at about shoulder width and toes should be pointing slightly outwards.\n3. Now place the barbell so it rests on the upper of your back.\n4. Grip the bar with a wide grip.\n5. Bend at the knees and ensure your back is straight and lift the bar off the rack.\n6. Take a step back so you are away from the rack.\n7. Keeping your head facing forward slowly lower your body down. Don't lean forward as you are coming down. Your buttocks should come out and drop straight down.\n8. Squat down until your knees are bent at a 90 degree angle and then push your body back up.\n9. Do not fully extend the knees when you stand up, and then repeat this for a number of reps.`,
    },
    {
      id: 26,
      title: 'cable cross over',
      category: 'chest',
      experience: 'beginner',
      img: './images/cablecrossover.jpg',
      vid: 'https://www.youtube.com/embed/taI4XduLpTk',
      desc: `1. Place both handles as high as possible and then choose a weight.\n2. Grip onto both handles with a neutral grip.\n3. Keep a straight back, and ensure your knees are slighly bent, and then pull the handles together so they are facing you.\n4. Controlling the tenstion slowly return the handles to the start position and repeat this exercise for a number of reps.`,
    },
    {
      id: 27,
      title: 'dumbbell flys',
      category: 'chest',
      experience: 'beginner',
      img: './images/dumbbellfly.jpg',
      vid: 'https://www.youtube.com/embed/eozdVDA78K0',
      desc: `1. Choose a desired weight. Lie down on the bench.\n2. Keep the dumbbells close to your chest. Inhale and then bring the dumbbells together with arms straight out infront of you.\n3. Once the dumbbells align with your chest, slowly lower the dumbbells by bringing them away from your body.\n4. Now repeat this exercise for a number of times.`,
    },
    {
      id: 28,
      title: 'dumbbell pullover',
      category: 'chest',
      experience: 'intermediate',
      img: './images/dumbbellpullover.jpg',
      vid: 'https://www.youtube.com/embed/zUVzVXMh9Nc',
      desc: `1. Rest against with both of your hands holding onto a dumbbell.\n2. You should be at a 90 degree angle against the bench. Ensure your back is straight, knees bent at 90 degrees, and feet are planted firmly on the ground.\n3. Grasping the dumbbell in both hands, extending out your arms ensure they are straight and that it is directly above your head.\n4. Bending only at the shoulders and making sure the arms are straight, controlling the tension lower the dumbbell until it reaches the bench.\n5. Controlling the tension slowly bring the dumbbell back up.\n6. Repeat this for a number of reps.`,
    },
    {
      id: 29,
      title: 'incline dumbbell bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/inclinedumbellbenchpress.jpg',
      vid: 'https://www.youtube.com/embed/07Bcqtib4FM',
      desc: `1. Choose a pair of dumbbells and sit down on an incline bench.\n2. Lie back on the bench and then bring the dumbbells together at the top.\n3. Controlling the tenstion lower the dumbbells down, the dumbbells should be about chest level.\n4. Contract the chest and push the dumbbells back up to the top.\n5. Repeat this exercise for a number of reps.`,
    },
    {
      id: 30,
      title: 'hammer strength machine incline bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/hammerstrength.jpg',
      vid: 'https://www.youtube.com/embed/ig0NyNlSce4',
      desc: `1. Sit down on the hammer strength machine, choose your desired weight.\n2. Place your palms on the handles, take a deep breathe, and bring your shoulder blades together.\n3. Push the handles till fully extended.\n4. Repeat this exercise for a number of reps.`,
    },
    {
      id: 31,
      title: 'pull up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/pullup.jpg',
      vid: 'https://www.youtube.com/embed/poyr8KenUfc',
      desc: `1. With your palms facing away from you grip onto the pull up bar, position your hands so they are roughly shoulder width.\n2. Inhale, tighten your glutes and engage your core. Drive your elbows straight down while depressing your shoulder blades and engaging your lats.\n3. Pull your chin till its over the bar and your lats are fully contracted , slowly lower yourself down while controlling the tenstion and repeat this exercise for a number of times.`,
    },
    {
      id: 32,
      title: 'wide grip pull up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/widegrippullup.jpeg',
      vid: 'https://www.youtube.com/embed/5oxviYmdHCY',
      desc: `1. With your palms facing away from you grip onto the pull up bar, position your hands so they are wider than shoulder width.\n2. Inhale, tighten your glutes and engage your core. Drive your elbows straight down while depressing your shoulder blades and engaging your lats.\n3. Pull your chin till its over the bar and your lats are fully contracted , slowly lower yourself down while controlling the tenstion and repeat this exercise for a number of times.`,
    },
    {
      id: 33,
      title: 'chin up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/chinup.jpg',
      vid: 'https://www.youtube.com/embed/b-ztMQpj8yc',
      desc: `1. With your palms facing towards you grip onto the pull up bar, position your hands so they are shoulder width.\n2. Inhale, tighten your glutes and engage your core. Drive your elbows straight down while depressing your shoulder blades and engaging your lats.\n3. Pull your chin till its over the bar and your lats are fully contracted , slowly lower yourself down while controlling the tenstion and repeat this exercise for a number of times.`,
    },
    {
      id: 34,
      title: 'side crunch',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/sidecrunch.jpg',
      vid: 'https://www.youtube.com/embed/w0OWFjfI3zM',
      desc: `1. Lie down on your side with your knees ontop of each other.\n2. Position your left hand behind your head for support and use your right hand to rest on your core.\n3. Tighten your abs to raise your upper body off the floor, controlling this tension slowly lower yourself back to the floor and do this exercise for a number of reps.\n4. Do this exercise on the opposite side too.`,
    },
    {
      id: 35,
      title: 'hanging leg raise',
      category: 'bodyweight',
      experience: 'advanced',
      img: './images/hanginglegraise.jpg',
      vid: 'https://www.youtube.com/embed/Pr1ieGZ5atk',
      desc: `1. Hang on a bar, tighten up your core. Keep your legs straight and infront of you, bring your legs as high as posible keeping legs straight.\n2. Hold the tension, and then slowly lower your legs back down.\n3. Repeat for a number of reps.`,
    },
    {
      id: 36,
      title: 'side plank',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/sideplank.jpg',
      vid: 'https://www.youtube.com/embed/NXr4Fw8q60o',
      desc: `1. Lie on your side with your legs placed ontop of each other.\n2. Using your elbow to rest on the floor.\n3. Lift up your hips so that your body is perfectly straight.\n4. Now maintain this position for as long as you can.\n5. Do this exercise on the opposite side as well.`,
    },
    {
      id: 37,
      title: 'bent over dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/bentoverdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/DhewkuU_95s',
      desc: `1. Choose your desired weights, and standing up hold the dumbbells with palms facing each other.\n2. Lean forward until the upper body is aligned with the floor.Bring elbows back behind the body while depressing shoulder blades.\n3. Pull the dumbbells towards you until your elbows go past your sides and then controlling the tension lower it back to the start position.\n4. Repeat this exercise for a number of times.`,
    },
    {
      id: 38,
      title: 't-bar row',
      category: 'back',
      experience: 'beginner',
      img: './images/tbar.jpg',
      vid: 'https://www.youtube.com/embed/j3Igk5nyZE4',
      desc: `1. Stand with your legs apart with the bar placed between your legs.\n2. Using a v-grip handle place the bar directly in the notch of the v.\n3. Lean forward until your upper body is slightly parallel with the floorve) bring your the elbows behind your body while retracting the shoulder blades.\n4. Pull the bar towards you until the plates touch your chest and then controlling the tension slowly lower the handle back to how you started.\n5. Repeat this for a number of reps.`,
    },
    {
      id: 39,
      title: 'behind neck lat pulldown',
      category: 'back',
      experience: 'intermediate',
      img: './images/behindneck.jpg',
      vid: 'https://www.youtube.com/embed/qayYjoMZQrw',
      desc: `1. Attach a wide grip onto the lap pulldown machine and then sit down.\n2. Gripping the handle with palms facing away and then contract the shoulder blades and flexing the elbow and extending the shoulder.\n3. Pull the bar behind your neck until it reaches the traps and then controlling the tension slowly bring the bar back up.\n4. Repeat this for a number of times.`,
    },
    {
      id: 40,
      title: 'superman',
      category: 'back',
      experience: 'beginner',
      img: './images/superman.jpg',
      vid: 'https://www.youtube.com/embed/cc6UVRS7PW4',
      desc: `1. Lie down with stomach touching the floor, with your hands by your side and feet close together.\n2. Engage your spinal erectors to stretch your lower back.\n3. Feeling the tenstion slowly return back to the starting position and repeat for a number of repetitions.`,
    },
    {
      id: 41,
      title: 'supported chest dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/supportedchest.jpg',
      vid: 'https://www.youtube.com/embed/fV78qqekQU4',
      desc: `1. Adjust a bench into a incline bench by bringin it up to 45 degrees and lie with your stomach against on the bench.\n2. Grasping a dumbbell in each hand with palms facing each other, drive your elbows past your body while retracting the shoulder blades.\n3. Pull the dumbbells so that they just go past your sides and then controlling the tension slowly lower the dumbbells.\n4. Repeat this exercise for a number of reps.`,
    },
    {
      id: 42,
      title: 'machine row',
      category: 'back',
      experience: 'beginner',
      img: './images/machinerow.jpg',
      vid: 'https://www.youtube.com/embed/TeFo51Q_Nsc',
      desc: `1. Place your chest against the padding.\n2. Sit down on the machine and place your hands on the handles.\n3. Maintaining this position , with your eyes facing forward and elbows by your side, slowly pull the handles back as far as you can.\n4. Hold this position, squeezing your shoulder blades together, and then controlling the tension slowly lower the handles back to how you started.\n5. Repeat for as many times as you like.`,
    },
    {
      id: 43,
      title: 'hammer curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standinghammer.jpg',
      vid: 'https://www.youtube.com/embed/TwD-YGVP4Bk',
      desc: `1. Standing with back straight hold onto the dumbbells by your side.\n2. Your palms should be facing towards your body.\n3. Ensure your elbows are slightly bent to focus the tension on biceps.\n4. Maintaining this position, slowly curl the dumbbells up as to chest area.\n5. Tighten the biceps once it reaches chest height, and then controlling this tension slowly lower the dumbbell down back to your side.\n6. Repeat this exercise for a number of times.`,
    },
    {
      id: 44,
      title: 'EZ Bar Preacher Curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/ezbar.jpg',
      vid: 'https://www.youtube.com/embed/Gydpcouclx8',
      desc: `1. Fix the seat so that your arms rest comfortably on the padding when sitting down.\n2. Place the weights onto the bar.\n3. Sit on the preacher bench and grasp the EZ bar with your hands shoulder width apart with palms facing up.\n4. Ensure that your back is straight and that your head is facing forward, lift the bar off the rack with your elbows slightly bent.\n5. Slowly bring the bar up until your forearms are at a 90 degree angle to the floor.\n6. Squeeze your bicep once it reaches the top, and then controlling the tension slowly lower it back down.\n7. Repeat for a number of reps.`,
    },
    {
      id: 45,
      title: 'reverse curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/reversecurl.jpeg',
      vid: 'https://www.youtube.com/embed/nRgxYX2Ve9w',
      desc: `1. Choose the desired weights and then standing up\n2. With palms facing down, inhale and curl the bar towards your shoulders.\n3. Once the biceps are fully contracted, controll the tension and slowly lower the bar back down.\n4. Repeat this for a number of reps.`,
    },
    {
      id: 46,
      title: 'dumbbell preacher curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/dumbbellpreacher.jpg',
      vid: 'https://www.youtube.com/embed/DoCWeUBA0Gs',
      desc: `1. Choose your desired weight and then place arm against the top of bench.\n2. Maintain this position with your palms facing up.\n3. Inhale and slowly bring the dumbbell down away from your shoulder.\n4. Once the bicep is fully extended, curl the dumbbell back up.\n5. Repeat this exercise on both sides for a number of times.`,
    },
    {
      id: 47,
      title: 'dumbbell hammer preacher curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/hammerpreacher.jpg',
      vid: 'https://www.youtube.com/embed/32W1sB5DkHY',
      desc: `1. Choose your desired weight and placing chest against preacher bench.\n2. Maintain this position with your palms facing up.\n3. Inhale and slowly bring the dumbbell down away from your shoulder.\n4. Once the bicep is fully extended, curl the dumbbell back up.\n5. Repeat this exercise for a number of times.`,
    },
    {
      id: 48,
      title: 'barbell drag curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/barbelldragcurl.jpg',
      vid: 'https://www.youtube.com/embed/LMdNTHH6G8I',
      desc: `1. Choose a weight and load it onto a bar and placing hands shoulder width apart.\n2. With your palms facing up, inhale and curl the barbell towards your shoulders.\n3. When you are pulling the bar upwards, ensure to keep it close to your upper body with elbows slighlty behind your body.\n4. Once the biceps are fully contracted, control the tension and slowly lower the bar back down.\n5. Repeat this for a number of times.`,
    },
    {
      id: 49,
      title: 'EZ Bar Skullcrusher',
      category: 'tricep',
      experience: 'beginner',
      img: './images/ezbarskullcrusher.jpg',
      vid: 'https://www.youtube.com/embed/d_KZxkY_0cM',
      desc: `1. Choose your desired weights and lie down on the bench.\n2. Ensure the bar is close to chest and push the bar till fully extended.\n3. Lower the bar towards your head by bending the elbows.\n4. Repeat for a number of times.`,
    },
    {
      id: 50,
      title: 'Lying Dumbbell Extension',
      category: 'tricep',
      experience: 'intermediate',
      img: './images/lyingdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/MO_03opCc0g',
      desc: `1. Grasping a pair of dumbbells lie down on the bench.\n2. Extend the dumbells above your head. Your palms should be facing each other.\n3. Ensure you are only bending at the elbows, ensure your elbows are fixed and pointing towards your hips, controlling the tension lower the dumbbells down beside your head until they are ear level.\n4. Holding this position, squeeze the triceps. Then bring the dumbbells back up.\n5. Do not fully extend your arms, and then repeat for a number of times.`,
    },
    {
      id: 51,
      title: 'French Press',
      category: 'tricep',
      experience: 'beginner',
      img: './images/frenchpress.jpg',
      vid: 'https://www.youtube.com/embed/JImgCWzCHwI',
      desc: `1. Grab an ez bar with desired weights.\n2. Gripping the barbell with palms facing down.\n3. Lift the bar above your head and bend your elbows slightly so the tension is focused on the triceps.\n4. Keeping your elbows fixed and pointing straight up, controlling the tension slowly lower the bar down behind your head as far as you can.\n5. Hold this position, and then controlling this tension slowly lower the bar.\n6. Do not fully extend your elbows, and then repeat this exercise for a number of times.`,
    },
    {
      id: 52,
      title: 'Bent Over Dumbbell Tricep Kickback',
      category: 'tricep',
      experience: 'beginner',
      img: './images/dumbbelltricep.jpg',
      vid: 'https://www.youtube.com/embed/ZO81bExngMI',
      desc: `1. Choose your desired dumbbell weight and then go to a bench. With one knee on bench and hand.\n2. Lean forward, bring the dumbbells up and then extend the elbows while flexing the triceps.\n3. Controlling the tension slowly lower the dumbbells back down and repeat this exercise for a number of times.`,
    },
    {
      id: 53,
      title: 'High Pulley Overhead Tricep Extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/overheadtricep.jpeg',
      vid: 'https://www.youtube.com/embed/NRENeEgaIgA',
      desc: `1. Attach a rope to the cable machine and move it as high as possilbe, while standing up.\n2. Stabding in a split stance, grip the rope overhead with palms facing each other, and lean forward.\n3. Extend the elbows and flex the triceps.\n4. Pull the rope downward until the elbows are almost fully extended and then controlling the tension slowly lower it back behind the head.\n5. Repeat for a number of times.`,
    },
    {
      id: 54,
      title: 'machine tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/machinetricepextension.jpg',
      vid: 'https://www.youtube.com/embed/bSp5GIsxwJU',
      desc: `1. Sit on the machine and grip onto the handles.\n2. Breathe out and press the handles away from you by extending the elbows.\n3. Control the tension and slowly lower the handles back to the starting position and repeat this action for a number of reps.`,
    },
    {
      id: 55,
      title: 'romanian deadlift',
      category: 'legs',
      experience: 'beginner',
      img: './images/romaniandeadlift.jpg',
      vid: 'https://www.youtube.com/embed/-m45n1_x32E',
      desc: `1. Place the bar over your feet and stand with your legs apart.\n2. With a double hand grip, deadlift the bar into place at the top with the hips and kness extended.\n3. Start the RDL by pushing your hips back and leaning forward until the bar is just below knee level.\n4. Drive through the entire foot and concentrate on pushing away from the floor.\n5. Go back to the starting position and repeat for as many repetitions as you desire.`,
    },
    {
      id: 56,
      title: 'Stiff Leg Deadlift',
      category: 'legs',
      experience: 'intermediate',
      img: './images/stifflegdeadlift.jpg',
      vid: 'https://www.youtube.com/embed/1uDiW5--rAE',
      desc: `1. Place the bar over your feet and stand in a hip width stance.\n2. Push your hips back and lean forward until your upper body is nearly 90 degrees with the floor.\n3. Reach down and grip the bar using a shoulder width, double overhand grip.\n4. Make sure your spine is neutral, shins are upright, and your hips are roughly the same height as your shoulders.\n5. Push through the entire foot and focus on pushing floor away from you.\n6. Make sure the bar is in a straight line as you extend the knees and hips.\n7. Once you have locked out the hips, reverse this action.\n8. Bring the bar back to the floor, reset, and repeat this exercise for a number of times.`,
    },
    {
      id: 57,
      title: 'sumo deadlift',
      category: 'legs',
      experience: 'beginner',
      img: './images/sumodeadlift.jpg',
      vid: 'https://www.youtube.com/embed/1v4r9hht_K4',
      desc: `1. Place the bar over your feet and stand in a wide stance.\n2. Push your hips back and lean forward until your upper body is approximately 90 degrees with the floor.\n3. Reach down and grip the bar with hands being a shoulder width apart, double overhand grip.\n4. Breathe in and pull up slightly on the bar while allowing your hips to drop just like a seesaw.\n5. As you drop the hips and pull up the bar, ensure your armpits are placed exactly over the bar.\n6. Push through the entire foot and concentrate on pushing the flower away from you.\n7. Once you have locked out the hips, reverse this action.
8. Bring the bar back to the floor, reset, and repeat this for a number of times.`,
    },
    {
      id: 58,
      title: 'dumbbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/dumbbellsquat.jpg',
      vid: 'https://www.youtube.com/embed/v_c67Omje48',
      desc: `1. Choose a pair of dumbbells and bring them to your sides.\n2. Ensure theres a slight bend on your knees and keep your eyes forward and back straight.\n3. Make sure your head is facing forward slowly bring your body down. However make sure you don't lean forward while coming down. Your buttocks should be pushed out and drop straight down.\n4. Squat down as far as you can , and then control the tension and slowly raise your body back up by driving through your heels.\n5. Do not fully extend the knees out when you stand up, and then repeat this exercise for a number of times.`,
    },
    {
      id: 59,
      title: 'dumbbell lunge',
      category: 'legs',
      experience: 'beginner',
      img: './images/dumbbelllunge.jpeg',
      vid: 'https://www.youtube.com/embed/COKYKgQ8KR0',
      desc: `1. Select a pair of dumbbells and ensure your back is straight while standing up with knees slightly bent.\n2. Holding onto the dumbells by your sides.\n3. Step forward with your left leg while ensuring you don't lose your balance and squat down.\n4. Make sure your upper body is straight.\n5. Then push your body back up through the use of your heel.\n6. Repeat this exercise on your other leg and repeat this for a number of times.`,
    },
    {
      id: 60,
      title: 'one leg dumbbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/oneleg.jpg',
      vid: 'https://www.youtube.com/embed/Ll60EDemwdQ',
      desc: `1. Stand in a split position while holding onto the dumbbells.\n2. Place your back foot on a bench.\n3. Lower yourself by flexing the front knee and keep doing this until the back knee reaches the floor.\n4. Push through the front foot and extend the knee as you go back to how you started.\n5. Repeat this for a number of times.`,
    },
  ];
  export default exercise;