const exercise = [
    {
      id: 1,
      title: 'sit up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/situp.jpg',
      vid: 'https://www.youtube.com/embed/jDwoBqPH0jk',
      desc: `1. Lay supine in a relaxed position with your knees up and hands across your chest.\n2. Exhale and squeeze your abs as you curl your upper body off the floor.\n3. Once your torso is perpendicular to the floor, slowly lower yourself back to the starting position.\n4. Repeat for the desired number of repetitions. `,
    },
    {
      id: 2,
      title: 'lying floor leg raise',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/lyingleg2.jpg',
      vid: 'https://www.youtube.com/embed/l4kQd9eWclE',
      desc: `1. Lay supine in a relaxed position with your legs straight and your hands underneath your lower back for support.\n2. Keep your legs straight and raise them towards your forehead while contracting your abdominals and exhaling.\n3. Once your abs are fully contracted and your legs are slightly above parallel, slowly lower your legs back to the starting position.\n4. Repeat for the desired number of repetitions. `,
    },
    {
      id: 3,
      title: 'pushup',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/pushup.jpg',
      vid: 'https://www.youtube.com/embed/KEFQyLkDYtI',
      desc: `1. Assume a quadruped position on the floor with your hands under your shoulders, toes tucked, and knees under hips.\n2. Extend one leg at a time and assume a pushup position with the legs straight, elbows extended, and head in a neutral position looking at the floor.\n3. Slowly descend to the floor by retracting the shoulder blades and unlocking the elbows.\n4. Descend until the upper arms are parallel or your chest touches the floor.\n5. Push back to the starting point by extending the elbows and driving your palms into the floor.\n6. Repeat for the desired number of repetitions.`,
    },
    {
      id: 4,
      title: 'bicycle',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/bicycle2.jpg',
      vid: 'https://www.youtube.com/embed/1we3bh9uhqY',
      desc: `1. Lay supine in a relaxed position with your arms behind your head and legs straight.\n2. Exhale as you raise one knee towards your face while driving the opposite elbow to the knee.\n3. Once your abs are fully contracted, slowly lower yourself back to the starting position and repeat on the opposite side.\n4. Repeat for as many reps you can do. `,
    },
    {
      id: 5,
      title: 'dumbbell bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/dumbbellbenchpress3.jpeg',
      vid: 'https://www.youtube.com/embed/dGqI0Z5ul4k',
      desc: `1. Pick up the dumbbells off the floor using a neutral grip (palms facing in). Position the ends of the dumbbells in your hip crease, and sit down on the bench.\n2. To get into position, lay back and keep the weights close to your chest. Once you are in position, take a deep breath, and press the dumbbells to lockout at the top.\n3. Slowly lower the dumbbells under control as far as comfortably possible (the handles should be about level with your chest).\n4. Contract the chest and push the dumbbells back up to the starting position.\n5. Repeat for the desired number of repetitions. `,
    },
    {
      id: 6,
      title: 'seated cable row',
      category: 'back',
      experience: 'beginner',
      img: './images/seatedcablerow.jpg',
      vid: 'https://www.youtube.com/embed/GZbfZ033f74',
      desc: `1. Set the appropriate weight on the weight stack and attach a close-grip bar or V-bar to the seated row machine.\n2. Grasp the bar with a neutral grip (palms facing in).\n3. Keeping your legs slightly bent and your back straight, pull the weight up slightly off the stack. You should be sitting straight upright with your shoulders back. This is the starting position.\n4. Keeping your body in position, pull the handle into your stomach.\n5. Pull your shoulder blades back, squeeze, pause, and then slowly lower the weight back to the starting position.\n6. Repeat for desired reps.`,
    },
    {
      id: 7,
      title: 'incline dumbbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/inclinedumbell.jpg',
      vid: 'https://www.youtube.com/embed/07Bcqtib4FM',
      desc: `1. Position an incline bench at roughly 55-65 degrees, select the desired weight from the rack, and sit upright with your back flat against the pad.\n2. Using a supinated (palms up) grip, take a deep breath and curl both dumbbells towards your shoulders.\n3. Once the biceps are fully shortened, slowly lower the weights back to the starting position.\n4. Repeat for the desired number of repetitions. `,
    },
    {
      id: 8,
      title: 'rope tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/ropetricep.jpg',
      vid: 'https://www.youtube.com/embed/LzwgB15UdO8',
      desc: `1. Attach a rope to a cable stack as high as possible and assume a standing position.\n2. Grasp the rope with a neutral grip (palms facing in) and lean forward slightly by hinging at the hips.\n3. Initiate the movement by extending the elbows and flexing the triceps.\n4. Pull the rope downward until the elbows are almost locked out and then slowly lower under control back to the starting position.\n5. Repeat for the desired number of repetitions. `,
    },
    {
      id: 9,
      title: 'seated leg curl',
      category: 'legs',
      experience: 'beginner',
      img: './images/seatedlegcurl.jpg',
      vid: 'https://www.youtube.com/embed/3BWiLFc8Dbg',
      desc: `1. Select the desired weight, then adjust the pad so it rests comfortably above the back of the heels.\n2. Tense up the hamstrings by taking the weight slightly off the stack. This is the starting position for the exercise.\n3. Take a deep breath, squeeze the hamstrings, and curl the weight up as far as possible while keeping the spine neutral.\n4. Slowly lower the weight back to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 10,
      title: 'barbell bench press',
      category: 'chest',
      experience: 'intermediate',
      img: './images/barbellbenchpress.jpg',
      vid: 'https://www.youtube.com/embed/4aVy2Xj6wYs',
      desc: `1. Lie flat on a bench and set your hands just outside of shoulder width.\n2. Set your shoulder blades by pinching them together and driving them into the bench.\n3. Take a deep breath and allow your spotter to help you with the lift off in order to maintain tightness through your upper back.\n4. Let the weight settle and ensure your upper back remains tight after lift off.\n5. Inhale and allow the bar to descend slowly by unlocking the elbows.\n6. Lower the bar in a straight line to the base of the sternum (breastbone) and touch the chest.\n7. Push the bar back up in a straight line by pressing yourself into the bench, driving your feet into the floor for leg drive, and extending the elbows.\n8. Repeat for the desired number of repetitions.`,
    },
    {
      id: 11,
      title: 'incline bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/inclinebench.jpg',
      vid: 'https://www.youtube.com/embed/dtNXLavPFo0',
      desc: `1. Lie flat on an incline bench and set your hands just outside of shoulder width.\n2. Set your shoulder blades by pinching them together and driving them into the bench.\n3. Take a deep breath and allow your spotter to help you with the lift off in order to maintain tightness through your upper back.\n4. Let the weight settle and ensure your upper back remains tight after lift off.\n5. Inhale and allow the bar to descend slowly by unlocking the elbows.\n6. Lower the bar in a straight line to the base of the sternum (breastbone) and touch the chest.\n7. Push the bar back up in a straight line by pressing yourself into the bench, driving your feet into the floor for leg drive, and extending the elbows.\n8. Repeat for the desired number of repetitions.`,
    },
    {
      id: 12,
      title: 'chest fly',
      category: 'chest',
      experience: 'beginner',
      img: './images/chestfly.jpg',
      vid: 'https://www.youtube.com/embed/Z57CtFmRMxA',
      desc: `1. The chest fly is a great machine for isolating the chest. Before you start, adjust the seat height so that the bottom of the arm pads are about level with your chest when you're sitting on the machine.\n2. Select the weight you want to use on the stack.\n3. Sit on the machine, grasp the handles and/or place your forearms on the padding. Take the weight off the stack slightly. This is the starting position for the exercise.\n4. Keeping your body fixed, slowly bring the forearm pads or handles together. Don't let them touch.\n5.. Squeeze the chest muscles for a count of 1-3, then slowly lower back to the starting position.\n6. Repeat for desired reps`,
    },
    {
      id: 13,
      title: 'chest dip',
      category: 'chest',
      experience: 'intermediate',
      img: './images/chestdip.jpg',
      vid: 'https://www.youtube.com/embed/FG1ENBFsdHU',
      desc: `1. Step up on the dip station (if possible) and position your hands with a neutral grip.\n2. Initiate the dip by unlocking the elbows and slowly lowering the body until the forearms are almost parallel with the floor.\n3. Control the descent to parallel and then drive back to the starting position by pushing through the palms.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 14,
      title: 'standing dumbbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standingdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/ykJmrZ5v0Oo',
      desc: `1. Assume the starting position for the standing dumbbell curl by grasping a pair of dumbbells and standing straight up, feet together and dumbbells by your side. The dumbbells should not be touching your body.\n2. Your palms should facing upwards.\n3. Take up the slack by bending the elbows slightly. Tension should be on the biceps.\n4. Slowly curl the dumbbells up as far as possible.\n5. Squeeze the biceps hard, and then slowly lower the dumbbells back down to the starting position.\n6. Repeat for desired reps.`,
    },
    {
      id: 15,
      title: 'standing barbell curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standingbar.jpg',
      vid: 'https://www.youtube.com/embed/kwG2ipFRgfo',
      desc: `1. The standing barbell curl is the cornerstone of many bicep building routines. Grasp a barbell or Olympic bar at around shoulder width apart using an underhand grip (palms facing up).\n2. Stand straight up, feet together (you may be more comfortable putting one foot back for stability), back straight, and with your arms fully extended.\n3. The bar should not be touching your body.\n4. Keeping your eyes facing forwards, elbows tucked in at your sides, and your body completely still, slowly curl the bar up.\n5. Squeeze your biceps hard at the top of the movement, and then slowly lower it back to the starting position.\n6. Repeat for desired reps.`,
    },
    {
      id: 16,
      title: 'bent over row',
      category: 'back',
      experience: 'beginner',
      img: './images/bentoverrow.jpg',
      vid: 'https://www.youtube.com/embed/paCfxhgW6bI',
      desc: `1. Assume a standing position while holding the bar using a double overhand grip.\n2.  Hinge forward until your torso is roughly parallel with the floor (or slightly above) and then begin the movement by driving the elbows behind the body while retracting the shoulder blades.\n3. Pull the bar towards your belly button until it touches your body and then slowly lower the bar back to the starting position under control.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 17,
      title: 'dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/dumbbellrow.jpg',
      vid: 'https://www.youtube.com/embed/-koP10y1qZI',
      desc: `1. Assume a kneeling position on the bench with your same side hand braced against the bench.\n2. Hold a dumbbell in the opposite hand with a neutral grip.\n3. Begin the movement by driving the elbow behind the body while retracting the shoulder blade.\n4. Pull the dumbbell towards your body until the elbow is at (or just past) the midline and then slowly lower the dumbbells back to the starting position under control.\n5. Repeat for the desired number of repetitions on both sides.`,
    },
    {
      id: 18,
      title: 'lat pulldown',
      category: 'back',
      experience: 'beginner',
      img: './images/latpulldown.jpg',
      vid: 'https://www.youtube.com/embed/u3gQT2aMVaI',
      desc: `1. Attach a wide grip handle to the lat pulldown machine and assume a seated position.\n2. Grasp the handle with a pronated grip (double overhand) and initiate the movement by depressing the shoulder blade and then flexing the elbow while extending the shoulder.\n3. Pull the handle towards your body until the elbows are in line with your torso and then slowly lower the handle back to the starting position under control.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 19,
      title: 'concentration curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/concentrationcurl.jpg',
      vid: 'https://www.youtube.com/embed/0AUGkch3tzc',
      desc: `1. Select the desired weight from the rack, and sit in an upright position on a flat bench.\n2. Hinge forward and position your elbow near the base of your knee. Place your free hand on the other knee to stabilize yourself.\n3. Using a supinated (palms facing up) grip, take a deep breath and curl the dumbbell towards your shoulder.\n4. Once the bicep is fully shortened, slowly lower the weight back to the starting position.\n5. Repeat for the desired number of repetitions on both sides.`,
    },
    {
      id: 20,
      title: 'straight bar tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/straightbar.jpeg',
      vid: 'https://www.youtube.com/embed/LlBqt8dksdk',
      desc: `1. Attach a straight bar to a cable stack as high as possible and assume a standing position.\n2. Grasp the straight bar with a pronated grip (palms facing down) and lean forward slightly by hinging at the hips.\n3. Initiate the movement by extending the elbows and flexing the triceps.\n4. Pull the handle downward until the elbows are almost locked out and then slowly lower under control back to the starting position.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 21,
      title: 'two arm standing dumbbell extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/standingdumbbelltricep2.jpg',
      vid: 'https://www.youtube.com/embed/VjmgzEmODnI',
      desc: `1. Select the desired weight from the rack and stand in an open area.\n2. To get into position, lift the dumbbell to the top of your shoulder, take a deep breath, overlap your hands around the dumbbell, then press it into position overhead.\n3. Maintain an overlapped grip and slowly lower the dumbbell behind your head by unlocking your elbows.\n4. Once your forearms reach parallel or just below, drive the dumbbell back to the starting point by extending the elbows and flexing the triceps.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 22,
      title: 'one arm standing dumbbell extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/onearm.jpeg',
      vid: 'https://www.youtube.com/embed/_gsUck-7M74',
      desc: `1. Get into the starting position for the standing one-arm dumbbell extension by grasping a dumbbell in your left hand and holding it above your head with your palm facing forward.\n2. Your elbow should be slightly bent. You can use your right arm to stabilize your body.\n3. Begin the movement by bending at the elbow only and slowly lowering the dumbbell behind your neck.\n4. Once the dumbbell is down as far as possible, slowly raise it back to the starting position.\n5. Do not lock your elbow out at the top of the movement, and then repeat for desired reps.`,
    },
    {
      id: 23,
      title: 'leg press',
      category: 'legs',
      experience: 'beginner',
      img: './images/legpress.jpg',
      vid: 'https://www.youtube.com/embed/VFk3RzndUEc',
      desc: `1. Load the machine with the desired weight and take a seat.\n2. Sit down and position your feet on the sled with a shoulder width stance.\n3. Take a deep breath, extend your legs, and unlock the safeties.\n4. Lower the weight under control until the legs are roughly 45 degrees or slightly below.\n5. Drive the weight back to the starting position by extending the knees but don’t forcefully lockout.\n6. Repeat for the desired number of repetitions.`,
    },
    {
      id: 24,
      title: 'seated calf raise',
      category: 'legs',
      experience: 'beginner',
      img: './images/seatedcalfraise.jpg',
      vid: 'https://www.youtube.com/embed/JbyjNymZOt0',
      desc: `1. Take a seat on the machine and place the balls of your feet on the platform with your toes pointed forward - your heels will naturally hang off. Position the base of quads under the knee pad and allow your hands to rest on top.\n2. Extend your ankles and release the safety bar.\n3. Lower the heels by bending back the ankles until the calves are fully stretched.\n4. Extend the ankles and exhale as you flex the calves.\n5. Repeat for the assigned number of repetitions.`,
    },
    {
      id: 25,
      title: 'barbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/barbellsquat.jpg',
      vid: 'https://www.youtube.com/embed/MVMNk0HiTMg',
      desc: `1. Set up for the exercise by setting the barbell to just below shoulder height and loading the weight you want to use.\n2. Stand under the bar with your feet at about shoulder width apart.\n3. Position the bar so that it is resting on the muscles on the top of your back, not on the back of your neck. The bar should feel comfortable. If it doesn't, try adding some padding to the bar.\n4. Now take your hands over the back and grip the bar with a wide grip for stability.\n5. You should now bend at the knees and straighten your back in preparation to take the weight off the rack.\n6. Keeping your back straight and eyes up, push up through the legs and take the weight off the rack.\n7. Take a small step back and stabilize yourself.\n8. Keeping your eyes facing forward slowly lower your body down. Don't lean forward as you come down. Your buttocks should come out and drop straight down.\n9. Squat down until your thighs are parallel with the floor, and then slowly raise your body back up by pushing through your heels.\n10. Do not lock the knees out when you stand up, and then repeat the movement.`,
    },
    {
      id: 26,
      title: 'cable cross over',
      category: 'chest',
      experience: 'beginner',
      img: './images/cablecrossover.jpg',
      vid: 'https://www.youtube.com/embed/taI4XduLpTk',
      desc: `1. Set both pulleys as high as possible and select the desired weight.\n2. Grasp both handles with a neutral grip and keep your feet in line with the pulleys.\n3. Remain upright, keep a slight bend in the elbows, move entirely at the shoulder joint, and pull both handles together in front of your body.\n4. Slowly lower back to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 27,
      title: 'dumbbell flys',
      category: 'chest',
      experience: 'beginner',
      img: './images/dumbbellfly.jpg',
      vid: 'https://www.youtube.com/embed/eozdVDA78K0',
      desc: `1. Pick up the dumbbells off the floor using a neutral grip (palms facing in). Position the ends of the dumbbells in your hip crease, and sit down on the bench.\n2. To get into position, lay back and keep the weights close to your chest. Once you are in position, take a deep breath, then press the dumbbells to lockout at the top.\n3. Slightly retract your shoulder blades, unlock your elbows, and slowly lower the dumbbells laterally while maintaining the angle at your elbow.\n4. Once the dumbbells reach chest level, reverse the movement by squeezing your pecs together and bringing the dumbbells back to their starting position.\n5. Without allowing the dumbbells to touch, start the next repetition, and continue until the set is completed.`,
    },
    {
      id: 28,
      title: 'dumbbell pullover',
      category: 'chest',
      experience: 'intermediate',
      img: './images/dumbbellpullover.jpg',
      vid: 'https://www.youtube.com/embed/zUVzVXMh9Nc',
      desc: `1. Grasp a dumbbell with both hands and position yourself on a flat bench with your shoulder blades resting on the bench.\n2. You should be at a 90 degree angle to the bench. Your back shoulder be straight, knees bent at 90 degrees, and feet firmly plated on the floor.\n3. Holding the dumbbell in both hands, straighten your arms so that dumbbell is directly overhead. This is the starting position.\n4. Bending at the shoulders only and keeping your arms straight, slowly lower the weight down behind your head until the dumbbell reaches the height of the bench.\n5. Slowly raise the dumbbell back to the starting position.\n6. Repeat for desired reps.`,
    },
    {
      id: 29,
      title: 'incline dumbbell bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/inclinedumbellbenchpress.jpg',
      vid: 'https://www.youtube.com/embed/07Bcqtib4FM',
      desc: `1. Pick up the dumbbells off the floor using a neutral grip (palms facing in). Position the ends of the dumbbells in your hip crease, and sit down on the edge of an incline bench.\n2. To get into position, lay back and keep the weights close to your chest. Once you are in position, take a deep breath, and press the dumbbells to lockout at the top.\n3. Slowly lower the dumbbells under control as far as comfortably possible (the handles should be about level with your chest).\n4. Contract the chest and push the dumbbells back up to the starting position.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 30,
      title: 'hammer strength machine incline bench press',
      category: 'chest',
      experience: 'beginner',
      img: './images/hammerstrength.jpg',
      vid: 'https://www.youtube.com/embed/ig0NyNlSce4',
      desc: `1. Sit on the end of the incline bench and lie back with the handles just below shoulder height. The handles should mimic the position of the bar when benching.\n2. Position your palms on the handles, inhale, and set your shoulder blades together on the bench.\n3. Press the handles to extension as you exhale but keep the shoulder blades packed.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 31,
      title: 'pull up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/pullup.jpg',
      vid: 'https://www.youtube.com/embed/poyr8KenUfc',
      desc: `1. Using a pronated grip, grasp the pull bar with a slightly wider than shoulder width grip.\n2. Take a deep breath, squeeze your glutes and brace your abs. Depress the shoulder blades and then drive the elbows straight down to the floor while activating the lats.\n3. Pull your chin towards the bar until the lats are fully contracted, then slowly lower yourself back to the start position and repeat for the desired number of repetitions.`,
    },
    {
      id: 32,
      title: 'wide grip pull up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/widegrippullup.jpeg',
      vid: 'https://www.youtube.com/embed/5oxviYmdHCY',
      desc: `1. Using a pronated grip, grasp the pull bar with a wider than shoulder width grip.\n2. Take a deep breath, squeeze your glutes and brace your abs. Depress the shoulder blades and then drive the elbows straight down to the floor while activating the lats.\n3. Pull your chin towards the bar until the lats are fully contracted, then slowly lower yourself back to the start position and repeat for as many repetitions you can do.`,
    },
    {
      id: 33,
      title: 'chin up',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/chinup.jpg',
      vid: 'https://www.youtube.com/embed/b-ztMQpj8yc',
      desc: `1. Using a supinated grip, grasp the bar with a shoulder width grip.\n2. Take a deep breath, squeeze your glutes and brace your abs. Depress the shoulder blades and then drive the elbows straight down to the floor while activating the lats.\n3. Pull your chin towards the bar until the lats are fully contracted, then slowly lower yourself back to the start position and repeat for the desired number of repetitions.`,
    },
    {
      id: 34,
      title: 'side crunch',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/sidecrunch.jpg',
      vid: 'https://www.youtube.com/embed/w0OWFjfI3zM',
      desc: `1. Lay supine in a relaxed position with your knees stacked to one side.\n2. Place your contralateral hand behind your head for support and use your free hand to palpate your abdominals.\n3. Initiate the movement by squeezing your abs to raise your torso off the floor, slowly lower yourself back to the starting position and complete the assigned number of repetitions.\n4. Repeat on the opposite side.`,
    },
    {
      id: 35,
      title: 'hanging leg raise',
      category: 'bodyweight',
      experience: 'advanced',
      img: './images/hanginglegraise.jpg',
      vid: 'https://www.youtube.com/embed/Pr1ieGZ5atk',
      desc: `1. Once you're hanging, tense up the mid section. While keeping your legs straight, raise your legs up slowly. You should raise your legs are high as possible.\n2. Pause for a second, and slowly lower your legs back to the starting position.\n3. Repeat for desired reps.`,
    },
    {
      id: 36,
      title: 'side plank',
      category: 'bodyweight',
      experience: 'beginner',
      img: './images/sideplank.jpg',
      vid: 'https://www.youtube.com/embed/NXr4Fw8q60o',
      desc: `1. Start by laying on your side with one hand on the floor and your feet on top of one another.\n2. If you prefer, you can rest on your elbow instead of your hand.\n3. Lift your hips up until your body is exactly straight.\n4. Now hold this position for as long as possible. You should feel this exercise in your abs and obliques.\n5. Complete the same for the opposite side of the body.`,
    },
    {
      id: 37,
      title: 'bent over dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/bentoverdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/DhewkuU_95s',
      desc: `1. Assume a standing position while holding a dumbbell in each hand with a neutral grip.\n2. Hinge forward until your torso is roughly parallel with the floor (or slightly above) and then begin the movement by driving the elbows behind the body while retracting the shoulder blades.\n3. Pull the dumbbells towards your body until the elbows are at (or just past) the midline and then slowly lower the dumbbells back to the starting position under control.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 38,
      title: 't-bar row',
      category: 'back',
      experience: 'beginner',
      img: './images/tbar.jpg',
      vid: 'https://www.youtube.com/embed/j3Igk5nyZE4',
      desc: `1. Assume a standing position with the bar positioned directly between your legs.\n2. Utilize a v-grip handle and place the bar directly in the notch of the v.\n3. Hinge forward until your torso is roughly parallel with the floor (or slightly above) and then begin the movement by driving the elbows behind the body while retracting the shoulder blades.\n4. Pull the bar towards your body until the plates touch your chest and then slowly lower the handle back to the starting position under control.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 39,
      title: 'behind neck lat pulldown',
      category: 'back',
      experience: 'intermediate',
      img: './images/behindneck.jpg',
      vid: 'https://www.youtube.com/embed/qayYjoMZQrw',
      desc: `1. Attach a wide grip handle to the lat pulldown machine and assume a seated position.\n2. Grasp the handle with a pronated grip (double overhand) and initiate the movement by depressing the shoulder blades and then flexing the elbow while extending the shoulder.\n3. Pull the handle behind your neck until it nearly touches at the base of your traps and then slowly lower the handle back to the starting position under control.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 40,
      title: 'superman',
      category: 'back',
      experience: 'beginner',
      img: './images/superman.jpg',
      vid: 'https://www.youtube.com/embed/cc6UVRS7PW4',
      desc: `1. Set up in a prone position with your hands by your side (or behind your back) and your feet together.\n2. Extend your lower back by contracting your spinal erectors.\n3. Slowly lower back to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 41,
      title: 'supported chest dumbbell row',
      category: 'back',
      experience: 'beginner',
      img: './images/supportedchest.jpg',
      vid: 'https://www.youtube.com/embed/fV78qqekQU4',
      desc: `1. Position an adjustable incline bench at 45 degrees and lie prone on the bench.\n2. Grab a dumbbell in each hand utilizing a neutral grip and then begin the movement by driving the elbows behind the body while retracting the shoulder blades.\n3. Pull the dumbbells towards your body until the elbows are at (or just past) the midline and then slowly lower the dumbbells back to the starting position under control.\n4. Repeat for the desired number of repetitions.`,
    },
    {
      id: 42,
      title: 'machine row',
      category: 'back',
      experience: 'beginner',
      img: './images/machinerow.jpg',
      vid: 'https://www.youtube.com/embed/TeFo51Q_Nsc',
      desc: `1. Your chest should be at the top of the pad.\n2. Sit down on the machine and grasp the handles with a neutral grip.\n3. Keeping your chest fixed on the pad, eyes facing forwards, and elbows in at your sides, slowly pull the handles back as far as possible.\n4. Pause, squeezing your shoulder blades together, and then slowly lower the weight back to the starting position without allowing it to drop.\n5. Repeat for desired reps.`,
    },
    {
      id: 43,
      title: 'hammer curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/standinghammer.jpg',
      vid: 'https://www.youtube.com/embed/TwD-YGVP4Bk',
      desc: `1. Set up by grasping a set of dumbbells and standing straight up with the dumbbells by your sides.\n2. You should be using a neutral grip, meaning your palms are facing your body.\n3. Bend your arms slightly to take tension into the biceps.\n4. Keeping your body fixed and elbows in at your sides, slowly curl the dumbbells up as far as possible.\n5. Squeeze the biceps at the top of the movement, and then slowly lower the weight back to the starting position.\n6. Repeat for desired reps.`,
    },
    {
      id: 44,
      title: 'EZ Bar Preacher Curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/ezbar.jpg',
      vid: 'https://www.youtube.com/embed/Gydpcouclx8',
      desc: `1. Adjust the seat on the preacher bench so that your upper arms sit comfortably on the padding when seated.\n2. Load the desired weight on the barbell.\n3. Sit on the preacher bench and grip the EZ bar with your hands shoulder width apart using an underhand (palms facing up) grip. (note: You can use a wide or narrow grip on this exercise)\n4. Keeping your back straight and eyes facing forward, take the weight off the rack so that you're supporting it with your arms slightly bent. This is the starting position.\n5. Slowly bring the weight up until your forearms are at a right angle to the floor.\n6. Squeeze the bicep at the top of the movement, and then slowly lower it back to the starting position.\n7. Repeat for desired reps.`,
    },
    {
      id: 45,
      title: 'reverse curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/reversecurl.jpeg',
      vid: 'https://www.youtube.com/embed/nRgxYX2Ve9w',
      desc: `1. Select the desired weight for ez bar and assume a shoulder width stance.\n2. Using a pronated (palms down) grip, take a deep breath and curl the ez bar towards your shoulders.\n3. Once the biceps are fully shortened, slowly lower the weight back to the starting position.\n4. Repeat for desired reps.`,
    },
    {
      id: 46,
      title: 'dumbbell preacher curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/dumbbellpreacher.jpg',
      vid: 'https://www.youtube.com/embed/DoCWeUBA0Gs',
      desc: `1. Select the desired weight from the rack, and sit in an upright position with your chest flat against the preacher bench.\n2. Keep your upper arm pressed into the pad and use a supinated (palms facing up) grip.\n3. Take a deep breath and slowly lower the dumbbell away from your shoulder.\n4. Once the bicep is fully lengthened, curl the weight back to the starting position.\n5. Repeat for the desired number of repetitions on both sides.`,
    },
    {
      id: 47,
      title: 'dumbbell hammer preacher curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/hammerpreacher.jpg',
      vid: 'https://www.youtube.com/embed/32W1sB5DkHY',
      desc: `1. Select the desired weight from the rack, and sit in an upright position with your chest flat against the preacher bench.\n2. Keep your upper arm pressed into the pad and use a neutral (palms facing up) grip.\n3. Take a deep breath and slowly lower the dumbbell away from your shoulder.\n4. Once the bicep is fully lengthened, curl the weight back to the starting position.\n5. Repeat for the desired number of repetitions on both sides.`,
    },
    {
      id: 48,
      title: 'barbell drag curl',
      category: 'biceps',
      experience: 'beginner',
      img: './images/barbelldragcurl.jpg',
      vid: 'https://www.youtube.com/embed/LMdNTHH6G8I',
      desc: `1. Select the desired weight, load it onto the bar, and assume a shoulder width stance.\n2. Using a supinated (palms up) grip, take a deep breath and curl the barbell towards your shoulders.\n3. As you pull the bar upwards, keep it close to your torso by allowing the elbows to drift slightly behind the body.\n4. Once the biceps are fully shortened, slowly lower the weight back to the starting position.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 49,
      title: 'EZ Bar Skullcrusher',
      category: 'tricep',
      experience: 'beginner',
      img: './images/ezbarskullcrusher.jpg',
      vid: 'https://www.youtube.com/embed/d_KZxkY_0cM',
      desc: `1. Select your desired weight and sit on the edge of a flat bench.\n2. To get into position, lay back and keep the bar close to your chest. Once you are supine, press the weight to lockout.\n3. Lower the weights towards your head by unlocking the elbows and allowing the ez bar to drop toward your forehead or just above.\n4. Once your forearms reach parallel or just below, reverse the movement by extending the elbows while flexing the triceps to lockout the weight.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 50,
      title: 'Lying Dumbbell Extension',
      category: 'tricep',
      experience: 'intermediate',
      img: './images/lyingdumbbell.jpg',
      vid: 'https://www.youtube.com/embed/MO_03opCc0g',
      desc: `1. Grab a pair of dumbbells and sit on the end of a flat bench with the dumbbells resting on your thighs.\n2. Lie back on the bench and extend the dumbbells above your head. The dumbbells should not be touching and you should be using a neutral grip (palms facing each other).\n3. Bending at the elbows only, keeping your elbows fixed and pointing at your hips, slowly lower the dumbbells down beside your head until they are about level with your ears.\n4. Pause and squeeze the triceps. Then raise the dumbbells back to the starting position.\n5. Do not lock the elbows out, and then repeat for desired reps.`,
    },
    {
      id: 51,
      title: 'French Press',
      category: 'tricep',
      experience: 'beginner',
      img: './images/frenchpress.jpg',
      vid: 'https://www.youtube.com/embed/JImgCWzCHwI',
      desc: `1. Set up for the french press by loading a barbell or EZ-bar with the appropriate amount of weight and placing it on the floor in front of you.\n2. Bend only at the knees and grasp the barbell with an overhand grip (palms facing down) with your hands about 8-12 inches apart.\n3. Stand up straight with the bar with your feet around shoulder-width apart and a slight bend in your knees.\n4. Lift the bar above your head and bend at your elbows slightly to take the tension onto your triceps. Your palms are now facing upward. This is the starting position for the exercise.\n5. Keeping your elbows fixed and pointing straight up toward the ceiling, slowly lower the bar down behind your head as far as comfortably possible.\n6. Pause, and then slowly raise the bar back to the starting position.\n7. Don't lock your elbows out, and then repeat the movement.`,
    },
    {
      id: 52,
      title: 'Bent Over Dumbbell Tricep Kickback',
      category: 'tricep',
      experience: 'beginner',
      img: './images/dumbbelltricep.jpg',
      vid: 'https://www.youtube.com/embed/ZO81bExngMI',
      desc: `1. Select the desired weight from the rack and stand in an open area.\n2. Hinge forward, row the dumbbells into position, then extend the elbows while flexing the triceps.\n3. Slowly lower the dumbbells back to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 53,
      title: 'High Pulley Overhead Tricep Extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/overheadtricep.jpeg',
      vid: 'https://www.youtube.com/embed/NRENeEgaIgA',
      desc: `1. Attach a rope to a cable stack as high as possible and assume a standing position.\n2. Utilize a split stance, grasp the rope overhead with a neutral grip (palms facing), and lean forward by hinging at the hips.\n3. Initiate the movement by extending the elbows and flexing the triceps.\n4. Pull the rope downward until the elbows are almost locked out and then slowly lower under control back to the starting position.\n5. Repeat for the desired number of repetitions.`,
    },
    {
      id: 54,
      title: 'machine tricep extension',
      category: 'tricep',
      experience: 'beginner',
      img: './images/machinetricepextension.jpg',
      vid: 'https://www.youtube.com/embed/bSp5GIsxwJU',
      desc: `1. Setup in a seated position with your hands in a neutral grip on the handles.\n2. Exhale and press the handles outward by extending the elbows.\n3. Slowly lower the handles back to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 55,
      title: 'romanian deadlift',
      category: 'legs',
      experience: 'beginner',
      img: './images/romaniandeadlift.jpg',
      vid: 'https://www.youtube.com/embed/-m45n1_x32E',
      desc: `1. Position the bar over the top of your shoelaces and assume a hip width stance.\n2. Assume a double overhand grip just outside of hip width and deadlift the weight into position at the top with the hips and knees locked out.\n3. Begin the RDL by pushing your hips back and hinging forward until the bar is just below knee height.\n4. Drive through the whole foot and focus on pushing the floor away.\n5. Return to the starting position and repeat for the desired number of repetitions.`,
    },
    {
      id: 56,
      title: 'Stiff Leg Deadlift',
      category: 'legs',
      experience: 'intermediate',
      img: './images/stifflegdeadlift.jpg',
      vid: 'https://www.youtube.com/embed/1uDiW5--rAE',
      desc: `1. Position the bar over the top of your shoelaces and assume a hip width stance.\n2. Push your hips back and hinge forward until your torso is nearly parallel with the floor.\n3. Reach down and grasp the bar using a shoulder width, double overhand grip.\n4. Ensure your spine is neutral, shin is vertical, and your hips are roughly the same height as your shoulders.\n5. Drive through the whole foot and focus on pushing the floor away.\n6. Ensure the bar tracks in a straight line as you extend the knees and hips.\n7. Once you have locked out the hips, reverse the movement by pushing the hips back and hinging forward.\n8. Return the bar to the floor, reset, and repeat for the desired number of repetitions.`,
    },
    {
      id: 57,
      title: 'sumo deadlift',
      category: 'legs',
      experience: 'beginner',
      img: './images/sumodeadlift.jpg',
      vid: 'https://www.youtube.com/embed/1v4r9hht_K4',
      desc: `1. Position the bar over the top of your shoelaces and assume a wide stance (determined by your hip structure and limb length).\n2. Push your hips back and hinge forward until your torso is nearly parallel with the floor.\n3. Reach down and grasp the bar using a shoulder width, double overhand grip.\n4. Inhale and pull up slightly on the bar while allowing your hips to drop in a seesaw fashion. This phenomenon is commonly referred to as “pulling the slack out of the bar”.\n5. As you drop the hips and pull up on the bar, set the lats (imagine you’re trying to squeeze oranges in your armpits) and ensure your armpits are positioned directly over the bar.\n6. Drive through the whole foot and focus on pushing the floor away.\n7. Ensure the bar tracks in a straight line as you extend the knees and hips.\n8. Once you have locked out the hips, reverse the movement by pushing the hips back and hinging forward.
9. Return the bar to the floor, reset, and repeat for the desired number of repetitions.`,
    },
    {
      id: 58,
      title: 'dumbbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/dumbbellsquat.jpg',
      vid: 'https://www.youtube.com/embed/v_c67Omje48',
      desc: `1. Set up for the dumbbell squat by choosing a pair of dumbbells and holding them down by your sides.\n2. Stand with a slight bend in your knees and your feet around shoulder width apart. Keep your head up and your back straight. This is the starting position.\n3. Keeping your eyes facing forward slowly lower your body down. Don't lean forward as you come down. Your buttocks should come out and drop straight down.\n4. Squat down as far as possible or at least until your thighs are parallel with the floor, and then slowly raise your body back up by pushing through your heels.\n5. Do not lock the knees out when you stand up, and then repeat the movement.`,
    },
    {
      id: 59,
      title: 'dumbbell lunge',
      category: 'legs',
      experience: 'beginner',
      img: './images/dumbbelllunge.jpeg',
      vid: 'https://www.youtube.com/embed/COKYKgQ8KR0',
      desc: `1. Choose a pair of dumbbells and stand up straight with a slight bend in your knees.\n2. Hold the dumbbells down at your sides. You are now in the starting position.\n3. Step forward with your left leg while maintaining your balance and squat down through your hips.\n4. Keep your torso straight and head up. Don't allow your knee to track out over your toes.\n5. Push yourself back to the starting position by using your heel to drive you.\n6. Repeat this movement with your right leg and then repeat for desired reps.`,
    },
    {
      id: 60,
      title: 'one leg dumbbell squat',
      category: 'legs',
      experience: 'intermediate',
      img: './images/oneleg.jpg',
      vid: 'https://www.youtube.com/embed/Ll60EDemwdQ',
      desc: `1. Set up in a split stance position while grasping dumbbells by your side with a neutral grip.\n2. Position the back foot on a bench or circular pad to increase the range of motion.\n3. Descend by flexing the front knee and continue until the back knee touches the ground directly beneath the hip.\n4. Drive through the front foot and extend the knee as you return to the starting position.\n5. Repeat for the desired number of repetitions.`,
    },
  ];
  export default exercise;